import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/antd.registry";
import Header from "@/component/header";
import "./globalStyle.css";
import Head from "next/head";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next xadApp",
  description: "Generated by create next app",
};

const test = {
  "@context": "https://schema.org",
  "@type": "Store",
  name: "Tiki",
  image: {
    "@type": "ImageObject",
    url: "https://salt.tikicdn.com/cache/w500/ts/upload/c0/8b/46/c3f0dc850dd93bfa7af7ada0cbd75dc0.png", // url hình ảnh
    width: 1080,
    height: 1080,
  },
  telephone: "19006035",
  url: "https://tiki.vn/",
  address: {
    "@type": "PostalAddress", //  địa chỉ bưu điện
    streetAddress: "52 Ut Tich, Ward 4, Tan Binh District, Ho Chi Minh City",
    addressLocality: "Ho Chi Minh",
    postalCode: "700000",
    addressRegion: "Ho Chi Minh",
    addressCountry: "VN",
  },
  priceRange: "1000 - 1000000000", // phạm vi giá
  openingHoursSpecification: [
    // thời gian mở cửa
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ],
      opens: "08:00",
      closes: "21:00",
    },
  ],
  geo: {
    "@type": "GeoCoordinates", // tọa độ
    latitude: "10.79664498748942", //vĩ độ
    longitude: "106.65856519879867", //kinh độ
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // suppressHydrationWarning
    <html lang="en">
      {/* <Head> */}
      <Script
        id="my-script"
        type="application/ld+json"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(test) }}
      />
      {/* </Head> */}

      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
